# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
sal_identify_objects <- function(indat, threshold, maxobj) {
    .Call('_harpSpatial_sal_identify_objects', PACKAGE = 'harpSpatial', indat, threshold, maxobj)
}

cumsum2d <- function(indat) {
    .Call('_harpSpatial_cumsum2d', PACKAGE = 'harpSpatial', indat)
}

cumsum2d_bin <- function(indat, threshold) {
    .Call('_harpSpatial_cumsum2d_bin', PACKAGE = 'harpSpatial', indat, threshold)
}

window_mean_from_cumsum <- function(indat, rad) {
    .Call('_harpSpatial_window_mean_from_cumsum', PACKAGE = 'harpSpatial', indat, rad)
}

windowMean <- function(indat, radius) {
    .Call('_harpSpatial_windowMean', PACKAGE = 'harpSpatial', indat, radius)
}

fss_from_fractions <- function(m1, m2) {
    .Call('_harpSpatial_fss_from_fractions', PACKAGE = 'harpSpatial', m1, m2)
}

score_fss <- function(obfield, fcfield, thresholds, window_sizes) {
    .Call('_harpSpatial_score_fss', PACKAGE = 'harpSpatial', obfield, fcfield, thresholds, window_sizes)
}

