# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

harpSpatial_basic_scores <- function(obfield, fcfield) {
    .Call('_harpSpatial_harpSpatial_basic_scores', PACKAGE = 'harpSpatial', obfield, fcfield)
}

#' @export
sal_identify_objects <- function(indat, threshold, maxobj) {
    .Call('_harpSpatial_sal_identify_objects', PACKAGE = 'harpSpatial', indat, threshold, maxobj)
}

cumsum2d <- function(indat) {
    .Call('_harpSpatial_cumsum2d', PACKAGE = 'harpSpatial', indat)
}

cumsum2d_bin <- function(indat, threshold) {
    .Call('_harpSpatial_cumsum2d_bin', PACKAGE = 'harpSpatial', indat, threshold)
}

window_mean_from_cumsum <- function(indat, rad) {
    .Call('_harpSpatial_window_mean_from_cumsum', PACKAGE = 'harpSpatial', indat, rad)
}

windowMean <- function(indat, radius) {
    .Call('_harpSpatial_windowMean', PACKAGE = 'harpSpatial', indat, radius)
}

fss_from_fractions <- function(m1, m2) {
    .Call('_harpSpatial_fss_from_fractions', PACKAGE = 'harpSpatial', m1, m2)
}

cpp_neighborhood_scores <- function(fcfield, obfield, thresholds, scales, comparator = "ge", includeLow = TRUE, includeHigh = TRUE, boundaryCondition = "zero_pad") {
    .Call('_harpSpatial_cpp_neighborhood_scores', PACKAGE = 'harpSpatial', fcfield, obfield, thresholds, scales, comparator, includeLow, includeHigh, boundaryCondition)
}

cpp_ens_fss <- function(geolistFcst, geofieldObs, threshold, scales, comparator = "ge", includeLow = TRUE, includeHigh = TRUE) {
    .Call('_harpSpatial_cpp_ens_fss', PACKAGE = 'harpSpatial', geolistFcst, geofieldObs, threshold, scales, comparator, includeLow, includeHigh)
}

harpSpatial_neighborhood_scores <- function(obfield, fcfield, thresholds, scales, comparator = "ge", includeLow = TRUE, includeHigh = TRUE, boundaryCondition = "zero_pad") {
    .Call('_harpSpatial_harpSpatial_neighborhood_scores', PACKAGE = 'harpSpatial', obfield, fcfield, thresholds, scales, comparator, includeLow, includeHigh, boundaryCondition)
}

harpSpatial_ens_fss <- function(geolistFcst, geofieldObs, threshold, scales, comparator = "ge", includeLow = TRUE, includeHigh = TRUE) {
    .Call('_harpSpatial_harpSpatial_ens_fss', PACKAGE = 'harpSpatial', geolistFcst, geofieldObs, threshold, scales, comparator, includeLow, includeHigh)
}

